# We are using CirceCI (see /.circleci/config.yml), but this does work so leaving it for reference
sudo: required

env:
  DOCKER_ORDERIMAGE=microsoft/pumrp-order
  DOCKER_CATALOGIMAGE=microsoft/pumrp-catalog
  DOCKER_ORDERTAG=1.0.0
  ORDER_PORT=8080
  CATALOG_PORT=8080

language: java

services:
  - docker

jobs:
  include:
  - stage: order service
    script:
    - chmod +x ./OrderSrvc/gradlew
    - ./OrderSrvc/gradlew build
    - docker build -f ./OrderSrvc/Dockerfile --build-arg port=$ORDER_PORT --build-arg VCS_REF=`git rev-parse --short HEAD` --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` -t $DOCKER_ORDERIMAGE:$DOCKER_ORDERTAG .
    - docker tag $DOCKER_ORDERIMAGE:$DOCKER_ORDERTAG $DOCKER_ORDERIMAGE:latest
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push $DOCKER_ORDERIMAGE:$DOCKER_ORDERTAG
    - docker push $DOCKER_ORDERIMAGE:latest
  - stage: catalog service
    script:
    - chmod +x ./CatalogSrvc/gradlew
    - ./CatalogSrvc/gradlew build
    - docker build -f ./CatalogSrvc/Dockerfile --build-arg port=$CATALOG_PORT --build-arg VCS_REF=`git rev-parse --short HEAD` --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` -t $DOCKER_ORDERIMAGE:$DOCKER_ORDERTAG .
    - docker tag $DOCKER_CATALOGIMAGE:$DOCKER_ORDERTAG $DOCKER_CATALOGIMAGE:latest
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push DOCKER_CATALOGIMAGE:$DOCKER_ORDERTAG
    - docker push DOCKER_CATALOGIMAGE:latest