version: 2
jobs:
  build:
    docker:
      - image: gradle:alpine

    environment:
      TEST_REPORTS: /tmp/test-reports
      DOCKER_ORDERIMAGE: microsoft/pumrp-order
      DOCKER_ORDERTAG: 1.0.0
      ORDER_PORT: 8080

    working_directory: ~/circleci

    branches:
      ignore:
        - develop
        - /feature-.*/

    steps:
      - checkout

      # Build Order Service
      - run: |
          cd OrderSrvc &&
          gradle build
      
      # Put test files to default CircleCI location
      - test:
         post:
           - mkdir -p $TEST_REPORTS/junit/
           - find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;

      #- run: |
      #    cp OrderSrvc/build/libs/*.jar /tmp/artifacts

      # Save artifacts
      #- store_artifacts:
      #    path: /tmp/artifacts
      #    destination: build

      # Upload test results
      #- store_test_results:
      #    path: /tmp/test-reports