resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604
  demands: java
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - DealerService/*

steps:
- task: Docker@1
  displayName: 'Build an image'
  inputs:
    azureSubscriptionEndpoint: $(SERVICE_CONNECTION)
    azureContainerRegistry: pumrpmicroacr.azurecr.io
    dockerFile: DealerService/Dockerfile
    useDefaultContext: false
    buildContext: '$(Build.SourcesDirectory)'
    addDefaultLabels: false
- task: Docker@1
  displayName: 'Push an image'
  inputs:
    azureSubscriptionEndpoint: $(SERVICE_CONNECTION)
    azureContainerRegistry: pumrpmicroacr.azurecr.io
    command: push