resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604
  demands: java
trigger:
  branches:
    include:
    - azure-pipelines
  paths:
    include:
    - DealerService/*

steps:
- task: Gradle@2
  displayName: 'gradlew build'
  inputs:
    gradleWrapperFile: DealerService/gradlew
    workingDirectory: DealerService
  continueOnError: true

- task: Docker@1
  displayName: 'Build an image'
  inputs:
    azureContainerRegistry: pumrpmicroacr.azurecr.io
    dockerFile: DealerService/Dockerfile
    useDefaultContext: false
    buildContext: '$(Build.SourcesDirectory)'
    addDefaultLabels: false

- task: Docker@1
  displayName: 'Push an image'
  inputs:
    azureContainerRegistry: pumrpmicroacr.azurecr.io
    command: 'Push an image'