trigger:
  branches:
    include:
    - azure-pipelines
  paths:
    include:
    - CatalogSrvc/*

steps:
- task: Gradle@2
  displayName: 'gradlew build'
  inputs:
    gradleWrapperFile: 'CatalogSrvc/gradlew'
    tasks: 'build'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: 'CatalogSrvc/**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

- script: |
    mkdir $(system.defaultworkingdirectory)/project
    docker run --rm -v $PWD/CatalogSrvc:/project -w $(system.defaultworkingdirectory)/project --name gradle gradle:3.4.1-jdk8-alpine gradle build --stacktrace 
    displayName: 'Docker build'

# - task: Docker@1
#   displayName: 'Docker build'
#   inputs:
#     dockerFile: CatalogSrvc/Dockerfile
#     useDefaultContext: false
#     buildContext: CatalogSrvc
#     imageName: '$(ACR_SERVER)/PUMRP-micro/catalog-service:$(Build.BuildId)'
#     includeLatestTag: true
# - task: Docker@1
#   displayName: 'Login to ACR'
#   inputs:
#     azureSubscriptionEndpoint: $(SERVICE_CONNECTION)
#     azureContainerRegistry: $(ACR_SERVER)
#     command: login
# - task: Docker@1
#   displayName: 'Docker push to ACR'
#   inputs:
#     command: 'push'
#     imageName: '$(ACR_SERVER)/PUMRP-micro/catalog-service:$(Build.BuildId)'
#     includeLatestTag: true