trigger:
  batch: true
  paths:
    include:
    - OrderSrvc/*

steps:
- task: Docker@1
  displayName: 'Docker build'
  inputs:
    dockerFile: OrderSrvc/Dockerfile
    useDefaultContext: false
    buildContext: OrderSrvc
    imageName: '$(ACR_SERVER)/PUMRP-micro/order-service:$(Build.BuildId)'
- task: Docker@1
  displayName: 'Login to ACR'
  inputs:
    azureSubscriptionEndpoint: $(SERVICE_CONNECTION)
    azureContainerRegistry: $(ACR_SERVER)
    command: login
- task: Docker@1
  displayName: 'Docker push to ACR'
  inputs:
    command: 'push'
    imageName: '$(ACR_SERVER)/PUMRP-micro/order-service:$(Build.BuildId)'