resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604
  demands: java
trigger:
  branches:
    include:
    - azure-pipelines
  paths:
    include:
    - ShipmentSrvc/*

steps:
- task: Gradle@2
  displayName: 'gradlew build'
  inputs:
    gradleWrapperFile: ShipmentSrvc/gradlew
    workingDirectory: ShipmentSrvc
  continueOnError: true

- task: Docker@1
  displayName: 'Build an image'
  inputs:
    azureSubscriptionEndpoint: 'CSE Americas Dev Crews (3fee811e-11bf-4b5c-9c62-a2f28b517724)'
    azureContainerRegistry: pumrpmicroacr.azurecr.io
    dockerFile: ShipmentSrvc/Dockerfile
    useDefaultContext: false
    buildContext: '$(Build.SourcesDirectory)'
    addDefaultLabels: false

- task: Docker@1
  displayName: 'Push an image'
  inputs:
    azureSubscriptionEndpoint: 'CSE Americas Dev Crews (3fee811e-11bf-4b5c-9c62-a2f28b517724)'
    azureContainerRegistry: pumrpmicroacr.azurecr.io
    command: 'Push an image'