apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.portName }}
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    app: {{ template "fullname" . }}
    tier: {{ .Values.labels.tier }}
    link: {{ .Values.labels.link }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentddeployment-config
data:
  fluentd.conf: |
    <source>
      type tail
      format none
      path /DealerApi/Dealer/EventLogs/DotNetAPI_Log.txt
      read_from_head true 
      tag count.format2
    </source>
    <match **>
      @type mongo
      host ####.documents.azure.com
      port 10250
      database mongocon #(required)
      collection dealer #(optional; default="untagged")
      user holmongo
      password ***********************
      ssl true
    </match>
